spring:
  application:
    name: highonmusic-songs
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: highonmusic
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081